### ISSUE TITLE
회원가입

### ISSUE THREAD

**Issue by YSChoi123** [PrroFeel/Today-Boss-Server#1]
## 문제 제기
- 인증된 유저들이 컨텐츠를 이용하기 위해 회원 가입이 필요하다

## 기능 요약
- 회원 가입

## 기능 설명
- 회원 가입을 통해 접근 권한을 부여하기 위한 로직이 들어갑니다

## 할 일 목록
- [x] jwt 설정
- [x] DTO, domain 작성
- [x] repository 작성
- [x] controller, service 작성
- [x] 회원가입 api 테스트

## 비고
- 스프링 시큐리티를 이용할 예정

**Comment by carrtt1** [comment]
태스크는 완료했으나 수정이 필요함
